/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as EnsemblesIndexImport } from './routes/ensembles/index'
import { Route as UsersUserIdImport } from './routes/users/$userId'
import { Route as EnsemblesCreateImport } from './routes/ensembles/create'
import { Route as EnsemblesEnsembleIdImport } from './routes/ensembles/$ensembleId'
import { Route as AuthSignUpImport } from './routes/auth/sign-up'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as ProfileEditIndexImport } from './routes/profile/edit/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const EnsemblesIndexRoute = EnsemblesIndexImport.update({
  id: '/ensembles/',
  path: '/ensembles/',
  getParentRoute: () => rootRoute,
} as any)

const UsersUserIdRoute = UsersUserIdImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRoute,
} as any)

const EnsemblesCreateRoute = EnsemblesCreateImport.update({
  id: '/ensembles/create',
  path: '/ensembles/create',
  getParentRoute: () => rootRoute,
} as any)

const EnsemblesEnsembleIdRoute = EnsemblesEnsembleIdImport.update({
  id: '/ensembles/$ensembleId',
  path: '/ensembles/$ensembleId',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const ProfileEditIndexRoute = ProfileEditIndexImport.update({
  id: '/profile/edit/',
  path: '/profile/edit/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof rootRoute
    }
    '/ensembles/$ensembleId': {
      id: '/ensembles/$ensembleId'
      path: '/ensembles/$ensembleId'
      fullPath: '/ensembles/$ensembleId'
      preLoaderRoute: typeof EnsemblesEnsembleIdImport
      parentRoute: typeof rootRoute
    }
    '/ensembles/create': {
      id: '/ensembles/create'
      path: '/ensembles/create'
      fullPath: '/ensembles/create'
      preLoaderRoute: typeof EnsemblesCreateImport
      parentRoute: typeof rootRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdImport
      parentRoute: typeof rootRoute
    }
    '/ensembles/': {
      id: '/ensembles/'
      path: '/ensembles'
      fullPath: '/ensembles'
      preLoaderRoute: typeof EnsemblesIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/edit/': {
      id: '/profile/edit/'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/ensembles/$ensembleId': typeof EnsemblesEnsembleIdRoute
  '/ensembles/create': typeof EnsemblesCreateRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/ensembles': typeof EnsemblesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/profile/edit': typeof ProfileEditIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/ensembles/$ensembleId': typeof EnsemblesEnsembleIdRoute
  '/ensembles/create': typeof EnsemblesCreateRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/ensembles': typeof EnsemblesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/profile/edit': typeof ProfileEditIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/ensembles/$ensembleId': typeof EnsemblesEnsembleIdRoute
  '/ensembles/create': typeof EnsemblesCreateRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/ensembles/': typeof EnsemblesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/profile/edit/': typeof ProfileEditIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/sign-up'
    | '/ensembles/$ensembleId'
    | '/ensembles/create'
    | '/users/$userId'
    | '/ensembles'
    | '/profile'
    | '/profile/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/sign-up'
    | '/ensembles/$ensembleId'
    | '/ensembles/create'
    | '/users/$userId'
    | '/ensembles'
    | '/profile'
    | '/profile/edit'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/sign-up'
    | '/ensembles/$ensembleId'
    | '/ensembles/create'
    | '/users/$userId'
    | '/ensembles/'
    | '/profile/'
    | '/profile/edit/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  EnsemblesEnsembleIdRoute: typeof EnsemblesEnsembleIdRoute
  EnsemblesCreateRoute: typeof EnsemblesCreateRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  EnsemblesIndexRoute: typeof EnsemblesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProfileEditIndexRoute: typeof ProfileEditIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  EnsemblesEnsembleIdRoute: EnsemblesEnsembleIdRoute,
  EnsemblesCreateRoute: EnsemblesCreateRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  EnsemblesIndexRoute: EnsemblesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProfileEditIndexRoute: ProfileEditIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/login",
        "/auth/sign-up",
        "/ensembles/$ensembleId",
        "/ensembles/create",
        "/users/$userId",
        "/ensembles/",
        "/profile/",
        "/profile/edit/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx"
    },
    "/ensembles/$ensembleId": {
      "filePath": "ensembles/$ensembleId.tsx"
    },
    "/ensembles/create": {
      "filePath": "ensembles/create.tsx"
    },
    "/users/$userId": {
      "filePath": "users/$userId.tsx"
    },
    "/ensembles/": {
      "filePath": "ensembles/index.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.tsx"
    },
    "/profile/edit/": {
      "filePath": "profile/edit/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
